version: "3.9"

services:
  flask-app:
    image: python:3.11
    container_name: flask_credit_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python app.py"
